# Generated by Django 5.2 on 2025-05-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_lessonmaterial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=1000)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="assignments_images/"
                    ),
                ),
                ("answer", models.TextField()),
            ],
        ),
    ]
